services:
  recsys_db:
    container_name: recsys_db
    image: postgres:17
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    ports:
      - "5432:5432"

  recsys_api:
    build:
      context: .
    container_name: recsys_api
    env_file: .env
    volumes:
      - .:/api
    ports:
      - "1051:1051"
    depends_on:
      - recsys_db   

     
